package com.github.donmor3000.filedialog.lib;

@SuppressWarnings("WeakerAccess")
abstract class MimeTypeUtil {
	static String getMIMEType(String filePath) {
		String type = "*/*";
		int dotIndex = filePath.lastIndexOf('.');
		if (dotIndex < 0) {
			return type;
		}
		String end = filePath.substring(dotIndex).toLowerCase();
		for (String[] mime : MIME_MapTable)
			if (end.equals(mime[1])) type = mime[0];
		return type;
	}

	static String[] trimMime(String[] mimes) {
		if (mimes == null) return new String[]{"*/*"};
		String[] u = new String[MIME_MapTable.length];
		int i = 0;
		for (String g : mimes) {
			if (g != null) {
				String v = getRootFromAlias(g);
				String p = v != null ? v : g;
				int x = p.indexOf('/') + 1;
				if (x < p.length() && p.charAt(x) == '*') {
					for (String[] e : MIME_MapTable) {
						if (e[0].startsWith(p.substring(0, x))) {
							u[i] = p;
							i++;
							break;
						}
					}
				} else {
					for (String[] e : MIME_MapTable) {
						if (e[0].equals(p)) {
							u[i] = p;
							i++;
							break;
						}
					}

				}
			}
		}
		if (i == 0) return new String[]{"*/*"};
		String[] v = new String[i];
		System.arraycopy(u, 0, v, 0, i);
		return v;
	}

	@SuppressWarnings("unused")
	static String[] trimMime(String mime) {
		return trimMime(new String[]{mime});
	}

	static String[] getExtensions(String mime) {
		String[] m = new String[MIME_MapTable.length];
		int k = 0;
		boolean all = false;
		if (mime != null && !mime.equals("")) {
			int w = mime.indexOf('/') + 1;
			if (mime.charAt(0) != '/' && mime.charAt(w) == '*')
				for (String[] i : MIME_MapTable) {
					if (i[0].startsWith(mime.substring(0, w))) {
						if (mime.charAt(0) == '*') all = true;
						else {
							m[k] = i[1];
							k++;
						}
					}
				}
			else
				for (String[] i : MIME_MapTable) {
					if (i[0].equals(mime)) {
						m[k] = i[1];
						k++;
					}
				}
		}
		if (all) {
			m[k] = "*/*";
			k++;
		}
		if (k == 0) return new String[]{"*/*"};
		String[] x = new String[k];
		System.arraycopy(m, 0, x, 0, k);
		return x;
	}

	static String[] getDescriptions(String[] mime, int det) {
		if (det == 0) return mime;
		String[] m = new String[mime.length];
		int k = 0;
		for (String mim : mime) {
			if (mim != null && !mim.equals("")) {
				String[] r = getExtensions(mim);
				StringBuilder t = new StringBuilder();
				for (String i : r) {
					t.append(i).append(';');
				}
				String v = t.toString();
				if (v.length() > 0 && det < 2)
					v = v.substring(0, v.length() - 1);
				else if (v.length() > 0)
					v = v.substring(0, v.length() - 1) + "(" + mim + ")";
				if (v.length() > 0) {
					m[k] = v;
					k++;
				}
			}
		}
		if (k == 0 && det > 1) return new String[]{".*(*/*)"};
		else if (k == 0) return new String[]{".*"};
		String[] x = new String[k];
		System.arraycopy(m, 0, x, 0, k);
		return x;
	}

	static boolean meetsMimeTypes(String fn, String mime) {
		for (String s : getExtensions(mime))
			if (s.equals(".*") || fn.toLowerCase().endsWith(s)) return true;
		return false;
	}

	@SuppressWarnings("WeakerAccess")
	static String getRootFromAlias(String mime) {
		for (String[] i : MIME_MapAlias)
			if (i[1].equals(mime))
				return i[0];
		return null;
	}

	static String formatFilename(String fn, String mimes, int index) {
		if (mimes.charAt(mimes.indexOf('/') + 1) == '*') return fn;
		String[] ext = getExtensions(mimes);
		for (String ex : ext)
			if (fn.endsWith(ex)) return fn;
		if (ext.length > 0) {
			if (index <0 && ext.length-index>=0 )
				return fn + ext[ext.length - index];
			else if (index >= 0 && index < ext.length)
				return fn + ext[index];
			else
				return fn + ext[0];
		}
		return fn;
	}

	static void traceAll() {
		for (String[] i : MIME_MapTable) {
			System.out.println(i[0]);
			System.out.println(i[1]);
		}
	}

	private static final String[][] MIME_MapTable =
			{
					{"application/andrew-inset", ".ez"},
					{"application/epub+zip", ".epub"},
					{"application/illustrator", ".ai"},
					{"application/mathematica", ".nb"},
					{"application/mathml+xml", ".mml"},
					{"application/mbox", ".mbox"},
					{"application/metalink+xml", ".metalink"},
					{"application/metalink4+xml", ".meta4"},
					{"application/octet-stream", ".bin"},
					{"application/x-partial-download", ".wkdownload"},
					{"application/x-partial-download", ".crdownload"},
					{"application/x-partial-download", ".part"},
					{"application/oda", ".oda"},
					{"application/x-wwf", ".wwf"},
					{"application/pdf", ".pdf"},
					{"application/xspf+xml", ".xspf"},
					{"application/x-windows-themepack", ".themepack"},
					{"audio/x-amzxml", ".amz"},
					{"audio/x-gsm", ".gsm"},
					{"audio/x-iriver-pla", ".pla"},
					{"application/pgp-encrypted", ".pgp"},
					{"application/pgp-encrypted", ".gpg"},
					{"application/pgp-encrypted", ".asc"},
					{"application/pgp-keys", ".skr"},
					{"application/pgp-keys", ".pkr"},
					{"application/pgp-keys", ".asc"},
					{"application/pgp-keys", ".pgp"},
					{"application/pgp-keys", ".gpg"},
					{"application/pgp-signature", ".asc"},
					{"application/pgp-signature", ".sig"},
					{"application/pgp-signature", ".pgp"},
					{"application/pgp-signature", ".gpg"},
					{"application/pkcs7-mime", ".p7c"},
					{"application/pkcs7-mime", ".p7m"},
					{"application/pkcs7-signature", ".p7s"},
					{"application/pkcs8", ".p8"},
					{"application/pkcs10", ".p10"},
					{"application/pkix-cert", ".cer"},
					{"application/pkix-crl", ".crl"},
					{"application/pkix-pkipath", ".pkipath"},
					{"application/postscript", ".ps"},
					{"application/relax-ng-compact-syntax", ".rnc"},
					{"application/rtf", ".rtf"},
					{"application/sieve", ".siv"},
					{"application/smil+xml", ".smil"},
					{"application/smil+xml", ".smi"},
					{"application/smil+xml", ".sml"},
					{"application/smil+xml", ".kino"},
					{"application/vnd.ms-wpl", ".wpl"},
					{"application/x-gedcom", ".ged"},
					{"application/x-gedcom", ".gedcom"},
					{"video/x-flv", ".flv"},
					{"video/x-javafx", ".fxm"},
					{"application/x-go-sgf", ".sgf"},
					{"application/x-xliff", ".xlf"},
					{"application/x-xliff", ".xliff"},
					{"application/x-yaml", ".yaml"},
					{"application/x-yaml", ".yml"},
					{"application/vnd.corel-draw", ".cdr"},
					{"application/vnd.hp-hpgl", ".hpgl"},
					{"application/vnd.hp-pcl", ".pcl"},
					{"application/vnd.lotus-1-2-3", ".123"},
					{"application/vnd.lotus-1-2-3", ".wk1"},
					{"application/vnd.lotus-1-2-3", ".wk3"},
					{"application/vnd.lotus-1-2-3", ".wk4"},
					{"application/vnd.lotus-1-2-3", ".wks"},
					{"application/vnd.lotus-wordpro", ".lwp"},
					{"application/vnd.ms-access", ".mdb"},
					{"application/vnd.ms-cab-compressed", ".cab"},
					{"application/vnd.ms-excel", ".xls"},
					{"application/vnd.ms-excel", ".xlc"},
					{"application/vnd.ms-excel", ".xll"},
					{"application/vnd.ms-excel", ".xlm"},
					{"application/vnd.ms-excel", ".xlw"},
					{"application/vnd.ms-excel", ".xla"},
					{"application/vnd.ms-excel", ".xlt"},
					{"application/vnd.ms-excel", ".xld"},
					{"application/vnd.ms-excel.addin.macroEnabled.12", ".xlam"},
					{"application/vnd.ms-excel.sheet.binary.macroEnabled.12", ".xlsb"},
					{"application/vnd.ms-excel.sheet.macroEnabled.12", ".xlsm"},
					{"application/vnd.ms-excel.template.macroEnabled.12", ".xltm"},
					{"application/vnd.ms-powerpoint", ".ppz"},
					{"application/vnd.ms-powerpoint", ".ppt"},
					{"application/vnd.ms-powerpoint", ".pps"},
					{"application/vnd.ms-powerpoint", ".pot"},
					{"application/vnd.ms-powerpoint.addin.macroEnabled.12", ".ppam"},
					{"application/vnd.ms-powerpoint.presentation.macroEnabled.12", ".pptm"},
					{"application/vnd.ms-powerpoint.slide.macroEnabled.12", ".sldm"},
					{"application/vnd.ms-powerpoint.slideshow.macroEnabled.12", ".ppsm"},
					{"application/vnd.ms-powerpoint.template.macroEnabled.12", ".potm"},
					{"application/vnd.ms-visio.drawing.main+xml", ".vsdx"},
					{"application/vnd.ms-visio.template.main+xml", ".vstx"},
					{"application/vnd.ms-visio.stencil.main+xml", ".vssx"},
					{"application/vnd.ms-visio.drawing.macroEnabled.main+xml", ".vsdm"},
					{"application/vnd.ms-visio.template.macroEnabled.main+xml", ".vstm"},
					{"application/vnd.ms-visio.stencil.macroEnabled.main+xml", ".vssm"},
					{"application/vnd.ms-word.document.macroEnabled.12", ".docm"},
					{"application/vnd.ms-word.template.macroEnabled.12", ".dotm"},
					{"application/oxps", ".oxps"},
					{"application/oxps", ".xps"},
					{"application/vnd.ms-works", ".wcm"},
					{"application/vnd.ms-works", ".wdb"},
					{"application/vnd.ms-works", ".wks"},
					{"application/vnd.ms-works", ".wps"},
					{"application/vnd.ms-works", ".xlr"},
					{"application/vnd.visio", ".vsd"},
					{"application/vnd.visio", ".vst"},
					{"application/vnd.visio", ".vsw"},
					{"application/vnd.visio", ".vss"},
					{"application/msword", ".doc"},
					{"application/msword-template", ".dot"},
					{"application/gml+xml", ".gml"},
					{"application/gnunet-directory", ".gnd"},
					{"application/vnd.ms-tnef", ".tnef"},
					{"application/vnd.ms-tnef", ".tnf"},
					{"application/vnd.stardivision.calc", ".sdc"},
					{"application/vnd.stardivision.chart", ".sds"},
					{"application/vnd.stardivision.draw", ".sda"},
					{"application/vnd.stardivision.impress", ".sdd"},
					{"application/vnd.stardivision.impress", ".sdp"},
					{"application/vnd.stardivision.mail", ".smd"},
					{"application/vnd.stardivision.math", ".smf"},
					{"application/vnd.stardivision.writer", ".sdw"},
					{"application/vnd.stardivision.writer", ".vor"},
					{"application/vnd.stardivision.writer", ".sgl"},
					{"application/vnd.sun.xml.calc", ".sxc"},
					{"application/vnd.sun.xml.calc.template", ".stc"},
					{"application/vnd.sun.xml.draw", ".sxd"},
					{"application/vnd.sun.xml.draw.template", ".std"},
					{"application/vnd.sun.xml.impress", ".sxi"},
					{"application/vnd.sun.xml.impress.template", ".sti"},
					{"application/vnd.sun.xml.math", ".sxm"},
					{"application/vnd.sun.xml.writer", ".sxw"},
					{"application/vnd.sun.xml.writer.global", ".sxg"},
					{"application/vnd.sun.xml.writer.template", ".stw"},
					{"application/vnd.oasis.opendocument.text", ".odt"},
					{"application/vnd.oasis.opendocument.text-flat-xml", ".fodt"},
					{"application/vnd.oasis.opendocument.text-template", ".ott"},
					{"application/vnd.oasis.opendocument.text-web", ".oth"},
					{"application/vnd.oasis.opendocument.text-master", ".odm"},
					{"application/vnd.oasis.opendocument.graphics", ".odg"},
					{"application/vnd.oasis.opendocument.graphics-flat-xml", ".fodg"},
					{"application/vnd.oasis.opendocument.graphics-template", ".otg"},
					{"application/vnd.oasis.opendocument.presentation", ".odp"},
					{"application/vnd.oasis.opendocument.presentation-flat-xml", ".fodp"},
					{"application/vnd.oasis.opendocument.presentation-template", ".otp"},
					{"application/vnd.oasis.opendocument.spreadsheet", ".ods"},
					{"application/vnd.oasis.opendocument.spreadsheet-flat-xml", ".fods"},
					{"application/vnd.oasis.opendocument.spreadsheet-template", ".ots"},
					{"application/vnd.oasis.opendocument.chart", ".odc"},
					{"application/vnd.oasis.opendocument.chart-template", ".otc"},
					{"application/vnd.oasis.opendocument.formula", ".odf"},
					{"application/vnd.oasis.opendocument.formula-template", ".otf"},
					{"application/vnd.oasis.opendocument.database", ".odb"},
					{"application/vnd.oasis.opendocument.image", ".odi"},
					{"application/vnd.openofficeorg.extension", ".oxt"},
					{"application/vnd.android.package-archive", ".apk"},
					{"application/vnd.symbian.install", ".sis"},
					{"x-epoc/x-sisx-app", ".sisx"},
					{"application/vnd.tcpdump.pcap", ".pcap"},
					{"application/vnd.tcpdump.pcap", ".cap"},
					{"application/vnd.tcpdump.pcap", ".dmp"},
					{"application/vnd.wordperfect", ".wp"},
					{"application/vnd.wordperfect", ".wp4"},
					{"application/vnd.wordperfect", ".wp5"},
					{"application/vnd.wordperfect", ".wp6"},
					{"application/vnd.wordperfect", ".wpd"},
					{"application/vnd.wordperfect", ".wpp"},
					{"application/x-spss-por", ".por"},
					{"application/x-spss-sav", ".sav"},
					{"application/x-spss-sav", ".zsav"},
					{"application/x-xbel", ".xbel"},
					{"application/x-7z-compressed", ".7z"},
					{"application/x-abiword", ".abw"},
					{"application/x-abiword", ".abw.CRASHED"},
					{"application/x-abiword", ".abw.gz"},
					{"application/x-abiword", ".zabw"},
					{"application/x-cue", ".cue"},
					{"application/x-amipro", ".sam"},
					{"application/x-aportisdoc", ".pdb"},
					{"application/x-aportisdoc", ".pdc"},
					{"application/x-applix-spreadsheet", ".as"},
					{"application/x-applix-word", ".aw"},
					{"application/x-archive", ".a"},
					{"application/x-archive", ".ar"},
					{"application/x-arj", ".arj"},
					{"application/x-asp", ".asp"},
					{"application/x-awk", ".awk"},
					{"application/x-bcpio", ".bcpio"},
					{"application/x-bittorrent", ".torrent"},
					{"application/x-blender", ".blender"},
					{"application/x-blender", ".blend"},
					{"application/x-blender", ".BLEND"},
					{"application/x-bzdvi", ".dvi.bz2"},
					{"application/x-bzip", ".bz2"},
					{"application/x-bzip", ".bz"},
					{"application/x-bzip-compressed-tar", ".tar.bz2"},
					{"application/x-bzip-compressed-tar", ".tar.bz"},
					{"application/x-bzip-compressed-tar", ".tbz2"},
					{"application/x-bzip-compressed-tar", ".tbz"},
					{"application/x-bzip-compressed-tar", ".tb2"},
					{"application/x-bzpdf", ".pdf.bz2"},
					{"application/x-bzpostscript", ".ps.bz2"},
					{"application/x-cbr", ".cbr"},
					{"application/x-cb7", ".cb7"},
					{"application/x-cbt", ".cbt"},
					{"application/x-cbz", ".cbz"},
					{"application/x-lrzip", ".lrz"},
					{"application/x-lrzip-compressed-tar", ".tar.lrz"},
					{"application/x-lrzip-compressed-tar", ".tlrz"},
					{"application/x-apple-diskimage", ".dmg"},
					{"application/x-raw-disk-image", ".raw-disk-image"},
					{"application/x-raw-disk-image", ".img"},
					{"application/x-raw-disk-image-xz-compressed", ".raw-disk-image.xz"},
					{"application/x-raw-disk-image-xz-compressed", ".img.xz"},
					{"application/x-cd-image", ".iso"},
					{"application/x-cd-image", ".iso9660"},
					{"application/x-cdrdao-toc", ".toc"},
					{"application/x-chess-pgn", ".pgn"},
					{"application/vnd.ms-htmlhelp", ".chm"},
					{"application/x-compress", ".Z"},
					{"application/x-compressed-tar", ".tar.gz"},
					{"application/x-compressed-tar", ".tgz"},
					{"application/x-cpio", ".cpio"},
					{"application/x-cpio-compressed", ".cpio.gz"},
					{"application/x-csh", ".csh"},
					{"application/x-dbf", ".dbf"},
					{"application/ecmascript", ".es"},
					{"application/x-saturn-rom", ".bin"},
					{"application/x-saturn-rom", ".iso"},
					{"application/x-dc-rom", ".dc"},
					{"application/x-nintendo-ds-rom", ".nds"},
					{"application/x-pc-engine-rom", ".pce"},
					{"application/x-wii-rom", ".iso"},
					{"application/x-wii-wad", ".wad"},
					{"application/x-gamecube-rom", ".iso"},
					{"application/vnd.debian.binary-package", ".deb"},
					{"application/vnd.debian.binary-package", ".udeb"},
					{"application/x-designer", ".ui"},
					{"text/x-qml", ".qml"},
					{"text/x-qml", ".qmltypes"},
					{"text/x-qml", ".qmlproject"},
					{"application/x-desktop", ".desktop"},
					{"application/x-desktop", ".kdelnk"},
					{"application/x-fictionbook+xml", ".fb2"},
					{"application/x-zip-compressed-fb2", ".fb2.zip"},
					{"application/x-dia-diagram", ".dia"},
					{"application/x-dia-shape", ".shape"},
					{"application/x-dvi", ".dvi"},
					{"application/x-e-theme", ".etheme"},
					{"application/x-egon", ".egon"},
					{"application/x-fluid", ".fl"},
					{"application/font-woff", ".woff"},
					{"application/x-font-type1", ".pfa"},
					{"application/x-font-type1", ".pfb"},
					{"application/x-font-type1", ".gsf"},
					{"application/x-font-afm", ".afm"},
					{"application/x-font-bdf", ".bdf"},
					{"application/x-font-linux-psf", ".psf"},
					{"application/x-gz-font-linux-psf", ".psf.gz"},
					{"application/x-font-pcf", ".pcf"},
					{"application/x-font-pcf", ".pcf.Z"},
					{"application/x-font-pcf", ".pcf.gz"},
					{"application/x-font-otf", ".otf"},
					{"application/x-font-speedo", ".spd"},
					{"application/x-font-ttf", ".ttf"},
					{"application/x-font-ttf", ".ttc"},
					{"application/x-font-ttx", ".ttx"},
					{"application/x-gameboy-rom", ".gb"},
					{"application/x-gameboy-rom", ".gbc"},
					{"application/x-gameboy-rom", ".cgb"},
					{"application/x-gameboy-rom", ".sgb"},
					{"application/x-gba-rom", ".gba"},
					{"application/x-gba-rom", ".agb"},
					{"application/x-genesis-rom", ".gen"},
					{"application/x-genesis-rom", ".smd"},
					{"application/x-genesis-rom", ".32x"},
					{"application/x-genesis-rom", ".mdx"},
					{"application/x-gettext-translation", ".gmo"},
					{"application/x-gettext-translation", ".mo"},
					{"application/x-gtk-builder", ".ui"},
					{"application/x-glade", ".glade"},
					{"application/x-gnucash", ".gnucash"},
					{"application/x-gnucash", ".gnc"},
					{"application/x-gnucash", ".xac"},
					{"application/x-gnumeric", ".gnumeric"},
					{"application/x-gnuplot", ".gp"},
					{"application/x-gnuplot", ".gplt"},
					{"application/x-gnuplot", ".gnuplot"},
					{"application/x-graphite", ".gra"},
					{"application/x-gzdvi", ".dvi.gz"},
					{"application/gzip", ".gz"},
					{"application/x-gzpdf", ".pdf.gz"},
					{"application/x-gzpostscript", ".ps.gz"},
					{"application/x-hdf", ".hdf"},
					{"application/x-hdf", ".hdf4"},
					{"application/x-hdf", ".h4"},
					{"application/x-hdf", ".hdf5"},
					{"application/x-hdf", ".h5"},
					{"application/x-java-archive", ".jar"},
					{"application/x-java", ".class"},
					{"application/x-java-jnlp-file", ".jnlp"},
					{"application/x-java-keystore", ".jks"},
					{"application/x-java-keystore", ".ks"},
					{"application/x-java-jce-keystore", ".jceks"},
					{"application/x-java-pack200", ".pack"},
					{"application/javascript", ".js"},
					{"application/javascript", ".jsm"},
					{"application/json", ".json"},
					{"application/jrd+json", ".jrd"},
					{"application/json-patch+json", ".json-patch"},
					{"application/ld+json", ".jsonld"},
					{"application/vnd.coffeescript", ".coffee"},
					{"application/x-jbuilder-project", ".jpr"},
					{"application/x-jbuilder-project", ".jpx"},
					{"application/x-karbon", ".karbon"},
					{"application/x-kchart", ".chrt"},
					{"application/x-kexi-connectiondata", ".kexic"},
					{"application/x-kexiproject-shortcut", ".kexis"},
					{"application/x-kexiproject-sqlite2", ".kexi"},
					{"application/x-kexiproject-sqlite3", ".kexi"},
					{"application/x-kformula", ".kfo"},
					{"application/x-killustrator", ".kil"},
					{"application/x-kivio", ".flw"},
					{"application/x-kontour", ".kon"},
					{"application/x-kpovmodeler", ".kpm"},
					{"application/x-kpresenter", ".kpr"},
					{"application/x-kpresenter", ".kpt"},
					{"application/x-krita", ".kra"},
					{"application/x-kspread", ".ksp"},
					{"application/x-kugar", ".kud"},
					{"application/x-kword", ".kwd"},
					{"application/x-kword", ".kwt"},
					{"application/x-lha", ".lha"},
					{"application/x-lha", ".lzh"},
					{"application/x-lhz", ".lhz"},
					{"text/vnd.trolltech.linguist", ".ts"},
					{"application/x-lyx", ".lyx"},
					{"application/x-lz4", ".lz4"},
					{"application/x-lzip", ".lz"},
					{"application/x-lzma", ".lzma"},
					{"application/x-lzma-compressed-tar", ".tar.lzma"},
					{"application/x-lzma-compressed-tar", ".tlz"},
					{"application/x-lzop", ".lzo"},
					{"application/x-qpress", ".qp"},
					{"application/zlib", ".zz"},
					{"application/x-magicpoint", ".mgp"},
					{"video/x-matroska", ".mkv"},
					{"video/x-matroska-3d", ".mk3d"},
					{"audio/x-matroska", ".mka"},
					{"video/webm", ".webm"},
					{"application/x-mimearchive", ".mhtml"},
					{"application/x-mimearchive", ".mht"},
					{"application/mxf", ".mxf"},
					{"text/x-ocl", ".ocl"},
					{"text/x-cobol", ".cbl"},
					{"text/x-cobol", ".cob"},
					{"application/x-mobipocket-ebook", ".mobi"},
					{"application/x-mobipocket-ebook", ".prc"},
					{"application/x-mif", ".mif"},
					{"application/x-ms-dos-executable", ".exe"},
					{"application/x-mswinurl", ".url"},
					{"application/x-mswrite", ".wri"},
					{"application/x-msx-rom", ".msx"},
					{"application/x-m4", ".m4"},
					{"application/x-n64-rom", ".n64"},
					{"application/x-n64-rom", ".z64"},
					{"application/x-n64-rom", ".v64"},
					{"application/x-nes-rom", ".nes"},
					{"application/x-nes-rom", ".nez"},
					{"application/x-nes-rom", ".unf"},
					{"application/x-nes-rom", ".unif"},
					{"application/x-netcdf", ".cdf"},
					{"application/x-netcdf", ".nc"},
					{"application/x-nzb", ".nzb"},
					{"application/x-object", ".o"},
					{"application/annodex", ".anx"},
					{"video/annodex", ".axv"},
					{"audio/annodex", ".axa"},
					{"application/ogg", ".ogx"},
					{"audio/ogg", ".oga"},
					{"audio/ogg", ".ogg"},
					{"audio/ogg", ".opus"},
					{"video/ogg", ".ogv"},
					{"video/ogg", ".ogg"},
					{"audio/x-vorbis+ogg", ".oga"},
					{"audio/x-vorbis+ogg", ".ogg"},
					{"audio/x-flac+ogg", ".oga"},
					{"audio/x-flac+ogg", ".ogg"},
					{"audio/x-opus+ogg", ".opus"},
					{"audio/x-speex+ogg", ".oga"},
					{"audio/x-speex+ogg", ".ogg"},
					{"audio/x-speex", ".spx"},
					{"video/x-theora+ogg", ".ogg"},
					{"video/x-ogm+ogg", ".ogm"},
					{"application/vnd.ms-publisher", ".pub"},
					{"application/x-msi", ".msi"},
					{"application/x-oleo", ".oleo"},
					{"application/x-pak", ".pak"},
					{"application/vnd.palm", ".prc"},
					{"application/vnd.palm", ".pdb"},
					{"application/vnd.palm", ".pqa"},
					{"application/vnd.palm", ".oprc"},
					{"application/x-par2", ".PAR2"},
					{"application/x-par2", ".par2"},
					{"application/x-perl", ".pl"},
					{"application/x-perl", ".PL"},
					{"application/x-perl", ".pm"},
					{"application/x-perl", ".al"},
					{"application/x-perl", ".perl"},
					{"application/x-perl", ".pod"},
					{"application/x-perl", ".t"},
					{"application/x-php", ".php"},
					{"application/x-php", ".php3"},
					{"application/x-php", ".php4"},
					{"application/x-php", ".php5"},
					{"application/x-php", ".phps"},
					{"application/x-pkcs7-certificates", ".p7b"},
					{"application/x-pkcs7-certificates", ".spc"},
					{"application/pkcs12", ".p12"},
					{"application/pkcs12", ".pfx"},
					{"application/x-planperfect", ".pln"},
					{"application/x-pocket-word", ".psw"},
					{"application/x-mps", ".mps"},
					{"application/x-pw", ".pw"},
					{"application/x-python-bytecode", ".pyc"},
					{"application/x-python-bytecode", ".pyo"},
					{"application/x-qtiplot", ".qti"},
					{"application/x-qtiplot", ".qti.gz"},
					{"application/x-quattropro", ".wb1"},
					{"application/x-quattropro", ".wb2"},
					{"application/x-quattropro", ".wb3"},
					{"application/x-quicktime-media-link", ".qtl"},
					{"application/x-qw", ".qif"},
					{"application/x-rar", ".rar"},
					{"application/x-dar", ".dar"},
					{"application/x-alz", ".alz"},
					{"text/x-reject", ".rej"},
					{"application/x-rpm", ".rpm"},
					{"application/x-source-rpm", ".src.rpm"},
					{"application/x-source-rpm", ".spm"},
					{"application/x-ruby", ".rb"},
					{"application/x-markaby", ".mab"},
					{"text/rust", ".rs"},
					{"application/x-shar", ".shar"},
					{"application/x-shared-library-la", ".la"},
					{"application/x-sharedlib", ".so"},
					{"application/x-shellscript", ".sh"},
					{"application/vnd.adobe.flash.movie", ".swf"},
					{"application/vnd.adobe.flash.movie", ".spl"},
					{"application/x-shorten", ".shn"},
					{"application/x-siag", ".siag"},
					{"image/x-skencil", ".sk"},
					{"image/x-skencil", ".sk1"},
					{"application/x-sms-rom", ".sms"},
					{"application/x-sms-rom", ".gg"},
					{"application/x-sms-rom", ".sg"},
					{"application/vnd.nintendo.snes.rom", ".sfc"},
					{"application/vnd.nintendo.snes.rom", ".smc"},
					{"application/x-stuffit", ".sit"},
					{"application/x-subrip", ".srt"},
					{"text/vtt", ".vtt"},
					{"application/x-sami", ".smi"},
					{"application/x-sami", ".sami"},
					{"text/x-microdvd", ".sub"},
					{"text/x-mpsub", ".sub"},
					{"text/x-ssa", ".ssa"},
					{"text/x-ssa", ".ass"},
					{"text/x-subviewer", ".sub"},
					{"text/x-iMelody", ".imy"},
					{"text/x-iMelody", ".ime"},
					{"application/x-smaf", ".mmf"},
					{"application/x-smaf", ".smaf"},
					{"text/x-mrml", ".mrml"},
					{"text/x-mrml", ".mrl"},
					{"audio/x-xmf", ".xmf"},
					{"application/x-sv4cpio", ".sv4cpio"},
					{"application/x-sv4crc", ".sv4crc"},
					{"application/x-tar", ".tar"},
					{"application/x-tar", ".gtar"},
					{"application/x-tar", ".gem"},
					{"application/x-tarz", ".tar.Z"},
					{"application/x-tarz", ".taz"},
					{"application/x-tex-gf", ".gf"},
					{"application/x-tex-pk", ".pk"},
					{"application/x-tgif", ".obj"},
					{"application/x-theme", ".theme"},
					{"application/x-trash", ".bak"},
					{"application/x-trash", ".old"},
					{"application/x-trash", ".sik"},
					{"text/troff", ".tr"},
					{"text/troff", ".roff"},
					{"text/troff", ".t"},
					{"application/x-troff-man", ".man"},
					{"application/x-tzo", ".tar.lzo"},
					{"application/x-tzo", ".tzo"},
					{"application/x-xz", ".xz"},
					{"application/x-xz-compressed-tar", ".tar.xz"},
					{"application/x-xz-compressed-tar", ".txz"},
					{"application/x-xzpdf", ".pdf.xz"},
					{"application/x-ustar", ".ustar"},
					{"application/x-wais-source", ".src"},
					{"application/x-wpg", ".wpg"},
					{"application/x-x509-ca-cert", ".der"},
					{"application/x-x509-ca-cert", ".crt"},
					{"application/x-x509-ca-cert", ".cert"},
					{"application/x-x509-ca-cert", ".pem"},
					{"application/x-zoo", ".zoo"},
					{"application/xhtml+xml", ".xhtml"},
					{"application/zip", ".zip"},
					{"application/x-ms-wim", ".wim"},
					{"application/x-ms-wim", ".swm"},
					{"audio/ac3", ".ac3"},
					{"audio/vnd.dts", ".dts"},
					{"audio/vnd.dts.hd", ".dtshd"},
					{"audio/AMR", ".amr"},
					{"audio/AMR-WB", ".awb"},
					{"audio/basic", ".au"},
					{"audio/basic", ".snd"},
					{"audio/prs.sid", ".sid"},
					{"audio/prs.sid", ".psid"},
					{"audio/x-aifc", ".aifc"},
					{"audio/x-aifc", ".aiffc"},
					{"audio/x-aiff", ".aiff"},
					{"audio/x-aiff", ".aif"},
					{"audio/x-ape", ".ape"},
					{"audio/x-it", ".it"},
					{"audio/flac", ".flac"},
					{"audio/x-wavpack", ".wv"},
					{"audio/x-wavpack", ".wvp"},
					{"audio/x-wavpack-correction", ".wvc"},
					{"audio/midi", ".mid"},
					{"audio/midi", ".midi"},
					{"audio/midi", ".kar"},
					{"audio/x-mo3", ".mo3"},
					{"audio/aac", ".aac"},
					{"audio/mp4", ".m4a"},
					{"audio/mp4", ".f4a"},
					{"video/mp4", ".mp4"},
					{"video/mp4", ".m4v"},
					{"video/mp4", ".f4v"},
					{"video/mp4", ".lrv"},
					{"audio/x-m4b", ".m4b"},
					{"audio/x-m4b", ".f4b"},
					{"video/3gpp", ".3gp"},
					{"video/3gpp", ".3gpp"},
					{"video/3gpp", ".3ga"},
					{"video/3gpp2", ".3g2"},
					{"video/3gpp2", ".3gp2"},
					{"video/3gpp2", ".3gpp2"},
					{"audio/x-mod", ".mod"},
					{"audio/x-mod", ".ult"},
					{"audio/x-mod", ".uni"},
					{"audio/x-mod", ".m15"},
					{"audio/x-mod", ".mtm"},
					{"audio/x-mod", ".669"},
					{"audio/x-mod", ".med"},
					{"audio/mp2", ".mp2"},
					{"audio/mpeg", ".mp3"},
					{"audio/mpeg", ".mpga"},
					{"audio/x-mpegurl", ".m3u"},
					{"audio/x-mpegurl", ".m3u8"},
					{"audio/x-mpegurl", ".vlc"},
					{"application/vnd.apple.mpegurl", ".m3u"},
					{"application/vnd.apple.mpegurl", ".m3u8"},
					{"audio/x-ms-asx", ".asx"},
					{"audio/x-ms-asx", ".wax"},
					{"audio/x-ms-asx", ".wvx"},
					{"audio/x-ms-asx", ".wmx"},
					{"audio/x-psf", ".psf"},
					{"audio/x-minipsf", ".minipsf"},
					{"audio/x-psflib", ".psflib"},
					{"audio/x-ms-wma", ".wma"},
					{"audio/x-musepack", ".mpc"},
					{"audio/x-musepack", ".mpp"},
					{"audio/x-musepack", ".mp+"},
					{"audio/vnd.rn-realaudio", ".ra"},
					{"audio/vnd.rn-realaudio", ".rax"},
					{"application/ram", ".ram"},
					{"video/vnd.rn-realvideo", ".rv"},
					{"video/vnd.rn-realvideo", ".rvx"},
					{"application/vnd.rn-realmedia", ".rm"},
					{"application/vnd.rn-realmedia", ".rmj"},
					{"application/vnd.rn-realmedia", ".rmm"},
					{"application/vnd.rn-realmedia", ".rms"},
					{"application/vnd.rn-realmedia", ".rmx"},
					{"application/vnd.rn-realmedia", ".rmvb"},
					{"image/vnd.rn-realpix", ".rp"},
					{"text/vnd.rn-realtext", ".rt"},
					{"audio/x-s3m", ".s3m"},
					{"audio/x-scpls", ".pls"},
					{"audio/x-stm", ".stm"},
					{"audio/x-voc", ".voc"},
					{"audio/x-wav", ".wav"},
					{"audio/x-xi", ".xi"},
					{"audio/x-xm", ".xm"},
					{"audio/x-tta", ".tta"},
					{"image/bmp", ".bmp"},
					{"image/vnd.wap.wbmp", ".wbmp"},
					{"image/cgm", ".cgm"},
					{"image/fax-g3", ".g3"},
					{"image/gif", ".gif"},
					{"image/ief", ".ief"},
					{"image/jpeg", ".jpeg"},
					{"image/jpeg", ".jpg"},
					{"image/jpeg", ".jpe"},
					{"image/jp2", ".jp2"},
					{"image/jp2", ".jpx"},
					{"image/jp2", ".jpf"},
					{"image/openraster", ".ora"},
					{"image/x-dds", ".dds"},
					{"image/x-exr", ".exr"},
					{"image/x-pict", ".pct"},
					{"image/x-pict", ".pict"},
					{"image/x-pict", ".pict1"},
					{"image/x-pict", ".pict2"},
					{"application/x-ufraw", ".ufraw"},
					{"image/x-adobe-dng", ".dng"},
					{"image/x-canon-crw", ".crw"},
					{"image/x-canon-cr2", ".cr2"},
					{"image/x-fuji-raf", ".raf"},
					{"image/x-kodak-dcr", ".dcr"},
					{"image/x-kodak-k25", ".k25"},
					{"image/x-kodak-kdc", ".kdc"},
					{"image/x-minolta-mrw", ".mrw"},
					{"image/x-nikon-nef", ".nef"},
					{"image/x-olympus-orf", ".orf"},
					{"image/x-panasonic-raw", ".raw"},
					{"image/x-panasonic-raw2", ".rw2"},
					{"image/x-pentax-pef", ".pef"},
					{"image/x-sigma-x3f", ".x3f"},
					{"image/x-sony-srf", ".srf"},
					{"image/x-sony-sr2", ".sr2"},
					{"image/x-sony-arw", ".arw"},
					{"image/png", ".png"},
					{"image/rle", ".rle"},
					{"image/svg+xml", ".svg"},
					{"image/svg+xml-compressed", ".svgz"},
					{"image/tiff", ".tif"},
					{"image/tiff", ".tiff"},
					{"image/vnd.dwg", ".dwg"},
					{"image/vnd.dxf", ".dxf"},
					{"image/vnd.ms-modi", ".mdi"},
					{"image/webp", ".webp"},
					{"image/x-3ds", ".3ds"},
					{"image/x-applix-graphics", ".ag"},
					{"image/x-bzeps", ".eps.bz2"},
					{"image/x-bzeps", ".epsi.bz2"},
					{"image/x-bzeps", ".epsf.bz2"},
					{"image/x-cmu-raster", ".ras"},
					{"image/x-compressed-xcf", ".xcf.gz"},
					{"image/x-compressed-xcf", ".xcf.bz2"},
					{"application/dicom", ".dcm"},
					{"application/x-docbook+xml", ".dbk"},
					{"application/x-docbook+xml", ".docbook"},
					{"image/vnd.djvu", ".djvu"},
					{"image/vnd.djvu", ".djv"},
					{"image/x-eps", ".eps"},
					{"image/x-eps", ".epsi"},
					{"image/x-eps", ".epsf"},
					{"image/fits", ".fits"},
					{"image/x-gzeps", ".eps.gz"},
					{"image/x-gzeps", ".epsi.gz"},
					{"image/x-gzeps", ".epsf.gz"},
					{"image/vnd.microsoft.icon", ".ico"},
					{"image/x-icns", ".icns"},
					{"image/x-ilbm", ".iff"},
					{"image/x-ilbm", ".ilbm"},
					{"image/x-ilbm", ".lbm"},
					{"image/x-jng", ".jng"},
					{"image/x-lwo", ".lwo"},
					{"image/x-lwo", ".lwob"},
					{"image/x-lws", ".lws"},
					{"image/x-macpaint", ".pntg"},
					{"image/x-msod", ".msod"},
					{"image/vnd.zbrush.pcx", ".pcx"},
					{"image/x-photo-cd", ".pcd"},
					{"image/x-portable-anymap", ".pnm"},
					{"image/x-portable-bitmap", ".pbm"},
					{"image/x-portable-graymap", ".pgm"},
					{"image/x-portable-pixmap", ".ppm"},
					{"image/vnd.adobe.photoshop", ".psd"},
					{"image/x-rgb", ".rgb"},
					{"image/x-sgi", ".sgi"},
					{"image/x-sun-raster", ".sun"},
					{"image/x-tga", ".icb"},
					{"image/x-tga", ".tga"},
					{"image/x-tga", ".tpic"},
					{"image/x-tga", ".vda"},
					{"image/x-tga", ".vst"},
					{"image/x-win-bitmap", ".cur"},
					{"application/x-navi-animation", ".ani"},
					{"image/x-emf", ".emf"},
					{"image/x-wmf", ".wmf"},
					{"image/x-xbitmap", ".xbm"},
					{"image/x-xcf", ".xcf"},
					{"image/x-xfig", ".fig"},
					{"image/x-xpixmap", ".xpm"},
					{"image/x-xwindowdump", ".xwd"},
					{"message/rfc822", ".eml"},
					{"model/vrml", ".vrm"},
					{"model/vrml", ".vrml"},
					{"model/vrml", ".wrl"},
					{"text/calendar", ".vcs"},
					{"text/calendar", ".ics"},
					{"text/css", ".css"},
					{"text/vcard", ".vcard"},
					{"text/vcard", ".vcf"},
					{"text/vcard", ".vct"},
					{"text/vcard", ".gcrd"},
					{"text/turtle", ".ttl"},
					{"text/x-txt2tags", ".t2t"},
					{"text/x-verilog", ".v"},
					{"text/x-svhdr", ".svh"},
					{"text/x-svsrc", ".sv"},
					{"text/x-vhdl", ".vhd"},
					{"text/x-vhdl", ".vhdl"},
					{"text/plain", ".txt"},
					{"text/plain", ".asc"},
					{"application/rdf+xml", ".rdf"},
					{"application/rdf+xml", ".rdfs"},
					{"application/rdf+xml", ".owl"},
					{"application/owl+xml", ".owx"},
					{"text/richtext", ".rtx"},
					{"application/rss+xml", ".rss"},
					{"application/atom+xml", ".atom"},
					{"text/x-opml+xml", ".opml"},
					{"text/sgml", ".sgml"},
					{"text/sgml", ".sgm"},
					{"text/spreadsheet", ".sylk"},
					{"text/spreadsheet", ".slk"},
					{"text/tab-separated-values", ".tsv"},
					{"text/vnd.graphviz", ".gv"},
					{"text/vnd.graphviz", ".dot"},
					{"text/vnd.sun.j2me.app-descriptor", ".jad"},
					{"text/vnd.wap.wml", ".wml"},
					{"text/vnd.wap.wmlscript", ".wmls"},
					{"application/x-ace", ".ace"},
					{"text/x-adasrc", ".adb"},
					{"text/x-adasrc", ".ads"},
					{"text/x-bibtex", ".bib"},
					{"text/x-c++hdr", ".hh"},
					{"text/x-c++hdr", ".hp"},
					{"text/x-c++hdr", ".hpp"},
					{"text/x-c++hdr", ".h++"},
					{"text/x-c++hdr", ".hxx"},
					{"text/x-c++src", ".cpp"},
					{"text/x-c++src", ".cxx"},
					{"text/x-c++src", ".cc"},
					{"text/x-c++src", ".C"},
					{"text/x-c++src", ".c++"},
					{"text/x-chdr", ".h"},
					{"text/x-cmake", ".cmake"},
					{"text/csv", ".csv"},
					{"text/csv-schema", ".csvs"},
					{"text/x-csrc", ".c"},
					{"text/x-csharp", ".cs"},
					{"text/x-vala", ".vala"},
					{"text/x-vala", ".vapi"},
					{"text/x-ooc", ".ooc"},
					{"text/x-dcl", ".dcl"},
					{"text/x-dsl", ".dsl"},
					{"text/x-dsrc", ".d"},
					{"text/x-dsrc", ".di"},
					{"application/xml-dtd", ".dtd"},
					{"text/x-eiffel", ".e"},
					{"text/x-eiffel", ".eif"},
					{"text/x-emacs-lisp", ".el"},
					{"text/x-erlang", ".erl"},
					{"text/x-fortran", ".f"},
					{"text/x-fortran", ".f90"},
					{"text/x-fortran", ".f95"},
					{"text/x-fortran", ".for"},
					{"text/x-genie", ".gs"},
					{"text/x-gettext-translation", ".po"},
					{"text/x-gettext-translation-template", ".pot"},
					{"text/html", ".html"},
					{"text/html", ".htm"},
					{"text/cache-manifest", ".manifest"},
					{"text/x-google-video-pointer", ".gvp"},
					{"text/x-haskell", ".hs"},
					{"text/x-idl", ".idl"},
					{"text/x-java", ".java"},
					{"text/x-ldif", ".ldif"},
					{"text/x-lilypond", ".ly"},
					{"text/x-literate-haskell", ".lhs"},
					{"text/x-log", ".log"},
					{"text/x-makefile", ".mk"},
					{"text/x-makefile", ".mak"},
					{"text/markdown", ".md"},
					{"text/markdown", ".mkd"},
					{"text/markdown", ".markdown"},
					{"text/x-moc", ".moc"},
					{"text/x-ms-regedit", ".reg"},
					{"text/x-mof", ".mof"},
					{"text/x-mup", ".mup"},
					{"text/x-mup", ".not"},
					{"text/x-objcsrc", ".m"},
					{"text/x-ocaml", ".ml"},
					{"text/x-ocaml", ".mli"},
					{"text/x-matlab", ".m"},
					{"text/x-modelica", ".mo"},
					{"text/x-pascal", ".p"},
					{"text/x-pascal", ".pas"},
					{"text/x-patch", ".diff"},
					{"text/x-patch", ".patch"},
					{"text/x-go", ".go"},
					{"text/x-python", ".py"},
					{"text/x-python", ".pyx"},
					{"text/x-python", ".wsgi"},
					{"text/x-lua", ".lua"},
					{"text/x-nfo", ".nfo"},
					{"text/x-rpm-spec", ".spec"},
					{"text/x-scala", ".scala"},
					{"text/x-scheme", ".scm"},
					{"text/x-scheme", ".ss"},
					{"text/x-setext", ".etx"},
					{"application/sql", ".sql"},
					{"text/x-tcl", ".tcl"},
					{"text/x-tcl", ".tk"},
					{"text/x-tex", ".tex"},
					{"text/x-tex", ".ltx"},
					{"text/x-tex", ".sty"},
					{"text/x-tex", ".cls"},
					{"text/x-tex", ".dtx"},
					{"text/x-tex", ".ins"},
					{"text/x-tex", ".latex"},
					{"text/x-texinfo", ".texi"},
					{"text/x-texinfo", ".texinfo"},
					{"text/x-troff-me", ".me"},
					{"text/x-troff-mm", ".mm"},
					{"text/x-troff-ms", ".ms"},
					{"text/x-uil", ".uil"},
					{"text/x-uuencode", ".uue"},
					{"text/x-xmi", ".xmi"},
					{"text/x-xslfo", ".fo"},
					{"text/x-xslfo", ".xslfo"},
					{"text/x-iptables", ".iptables"},
					{"application/xslt+xml", ".xsl"},
					{"application/xslt+xml", ".xslt"},
					{"application/xml", ".xml"},
					{"application/xml", ".xbl"},
					{"application/xml", ".xsd"},
					{"application/xml", ".rng"},
					{"application/xml-external-parsed-entity", ".ent"},
					{"video/dv", ".dv"},
					{"video/mp2t", ".m2t"},
					{"video/mp2t", ".m2ts"},
					{"video/mp2t", ".ts"},
					{"video/mp2t", ".mts"},
					{"video/mp2t", ".cpi"},
					{"video/mp2t", ".clpi"},
					{"video/mp2t", ".mpl"},
					{"video/mp2t", ".mpls"},
					{"video/mp2t", ".bdm"},
					{"video/mp2t", ".bdmv"},
					{"video/mpeg", ".mpeg"},
					{"video/mpeg", ".mpg"},
					{"video/mpeg", ".mp2"},
					{"video/mpeg", ".mpe"},
					{"video/mpeg", ".vob"},
					{"video/vnd.mpegurl", ".m1u"},
					{"video/vnd.mpegurl", ".m4u"},
					{"video/vnd.mpegurl", ".mxu"},
					{"video/quicktime", ".qt"},
					{"video/quicktime", ".mov"},
					{"video/quicktime", ".moov"},
					{"video/quicktime", ".qtvr"},
					{"image/x-quicktime", ".qtif"},
					{"image/x-quicktime", ".qif"},
					{"video/vnd.vivo", ".viv"},
					{"video/vnd.vivo", ".vivo"},
					{"video/x-anim", ".anim"},
					{"video/x-flic", ".fli"},
					{"video/x-flic", ".flc"},
					{"application/x-hwp", ".hwp"},
					{"application/x-hwt", ".hwt"},
					{"video/x-mng", ".mng"},
					{"application/vnd.ms-asf", ".asf"},
					{"application/x-netshow-channel", ".nsc"},
					{"video/x-ms-wmv", ".wmv"},
					{"video/x-msvideo", ".avi"},
					{"video/x-msvideo", ".avf"},
					{"video/x-msvideo", ".divx"},
					{"video/x-nsv", ".nsv"},
					{"application/sdp", ".sdp"},
					{"video/x-sgi-movie", ".movie"},
					{"application/vnd.emusic-emusic_package", ".emp"},
					{"application/vnd.google-earth.kml+xml", ".kml"},
					{"application/vnd.google-earth.kmz", ".kmz"},
					{"application/x-ica", ".ica"},
					{"application/vnd.mozilla.xul+xml", ".xul"},
					{"application/x-xpinstall", ".xpi"},
					{"application/vnd.openxmlformats-officedocument.wordprocessingml.document", ".docx"},
					{"application/vnd.openxmlformats-officedocument.wordprocessingml.template", ".dotx"},
					{"application/vnd.openxmlformats-officedocument.presentationml.presentation", ".pptx"},
					{"application/vnd.openxmlformats-officedocument.presentationml.slide", ".sldx"},
					{"application/vnd.openxmlformats-officedocument.presentationml.slideshow", ".ppsx"},
					{"application/vnd.openxmlformats-officedocument.presentationml.template", ".potx"},
					{"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", ".xlsx"},
					{"application/vnd.openxmlformats-officedocument.spreadsheetml.template", ".xltx"},
					{"application/x-t602", ".602"},
					{"application/x-cisco-vpn-settings", ".pcf"},
					{"application/vnd.iccprofile", ".icc"},
					{"application/vnd.iccprofile", ".icm"},
					{"application/x-it87", ".it87"},
					{"application/x-ccmx", ".ccmx"},
					{"application/winhlp", ".hlp"},
					{"application/x-trig", ".trig"},
					{"application/x-iwork-keynote-sffkey", ".key"},
					{"application/x-pagemaker", ".p65"},
					{"application/x-pagemaker", ".pm"},
					{"application/x-pagemaker", ".pm6"},
					{"application/x-pagemaker", ".pmd"},
					{"application/x-doom-wad", ".wad"},
					{"application/x-amiga-disk-format", ".adf"},
					{"application/vnd.squashfs", ".sqsh"},
					{"application/vnd.snap", ".snap"},
					{"*/*", ".*"}
			};
	private static final String[][] MIME_MapAlias =
			{
					{"application/mathematica", "application/x-mathematica"},
					{"application/mathml+xml", "text/mathml"},
					{"application/x-wwf", "application/wwf"},
					{"application/pdf", "application/x-pdf"},
					{"application/pdf", "image/pdf"},
					{"application/pdf", "application/acrobat"},
					{"application/xspf+xml", "application/x-xspf+xml"},
					{"application/pgp-encrypted", "application/pgp"},
					{"application/relax-ng-compact-syntax", "application/x-rnc"},
					{"application/rtf", "text/rtf"},
					{"application/smil+xml", "application/smil"},
					{"application/x-gedcom", "text/gedcom"},
					{"video/x-flv", "application/x-flash-video"},
					{"video/x-flv", "flv-application/octet-stream"},
					{"video/x-flv", "video/flv"},
					{"application/x-yaml", "text/yaml"},
					{"application/x-yaml", "text/x-yaml"},
					{"application/vnd.corel-draw", "application/cdr"},
					{"application/vnd.corel-draw", "application/coreldraw"},
					{"application/vnd.corel-draw", "application/x-cdr"},
					{"application/vnd.corel-draw", "application/x-coreldraw"},
					{"application/vnd.corel-draw", "image/cdr"},
					{"application/vnd.corel-draw", "image/x-cdr"},
					{"application/vnd.corel-draw", "zz-application/zz-winassoc-cdr"},
					{"application/vnd.lotus-1-2-3", "application/x-lotus123"},
					{"application/vnd.lotus-1-2-3", "application/x-123"},
					{"application/vnd.lotus-1-2-3", "application/lotus123"},
					{"application/vnd.lotus-1-2-3", "application/wk1"},
					{"application/vnd.lotus-1-2-3", "zz-application/zz-winassoc-123"},
					{"application/vnd.ms-access", "application/x-msaccess"},
					{"application/vnd.ms-access", "application/msaccess"},
					{"application/vnd.ms-access", "application/vnd.msaccess"},
					{"application/vnd.ms-access", "application/x-msaccess"},
					{"application/vnd.ms-access", "application/mdb"},
					{"application/vnd.ms-access", "application/x-mdb"},
					{"application/vnd.ms-access", "zz-application/zz-winassoc-mdb"},
					{"application/vnd.ms-cab-compressed", "zz-application/zz-winassoc-cab"},
					{"application/vnd.ms-excel", "application/msexcel"},
					{"application/vnd.ms-excel", "application/x-msexcel"},
					{"application/vnd.ms-excel", "zz-application/zz-winassoc-xls"},
					{"application/vnd.ms-powerpoint", "application/powerpoint"},
					{"application/vnd.ms-powerpoint", "application/mspowerpoint"},
					{"application/vnd.ms-powerpoint", "application/x-mspowerpoint"},
					{"application/oxps", "application/vnd.ms-xpsdocument"},
					{"application/msword", "application/vnd.ms-word"},
					{"application/msword", "application/x-msword"},
					{"application/msword", "zz-application/zz-winassoc-doc"},
					{"application/vnd.ms-tnef", "application/ms-tnef"},
					{"application/vnd.stardivision.writer", "application/vnd.stardivision.writer-global"},
					{"application/vnd.oasis.opendocument.database", "application/vnd.sun.xml.base"},
					{"application/vnd.tcpdump.pcap", "application/x-pcap"},
					{"application/vnd.tcpdump.pcap", "application/pcap"},
					{"application/vnd.wordperfect", "application/x-wordperfect"},
					{"application/vnd.wordperfect", "application/wordperfect"},
					{"application/x-spss-sav", "application/x-spss-savefile"},
					{"application/x-bzip", "application/x-bzip2"},
					{"application/x-cd-image", "application/x-iso9660-image"},
					{"application/vnd.ms-htmlhelp", "application/x-chm"},
					{"application/x-dbf", "application/x-dbase"},
					{"application/x-dbf", "application/dbf"},
					{"application/x-dbf", "application/dbase"},
					{"application/ecmascript", "text/ecmascript"},
					{"application/x-wii-rom", "application/x-wii-iso-image"},
					{"application/x-wii-rom", "application/x-wbfs"},
					{"application/x-wii-rom", "application/x-wia"},
					{"application/x-gamecube-rom", "application/x-gamecube-iso-image"},
					{"application/vnd.debian.binary-package", "application/x-deb"},
					{"application/vnd.debian.binary-package", "application/x-debian-package"},
					{"application/x-desktop", "application/x-gnome-app-info"},
					{"application/x-fictionbook+xml", "application/x-fictionbook"},
					{"application/gzip", "application/x-gzip"},
					{"application/x-java-archive", "application/x-jar"},
					{"application/x-java-archive", "application/java-archive"},
					{"application/x-java", "application/java"},
					{"application/x-java", "application/java-byte-code"},
					{"application/x-java", "application/java-vm"},
					{"application/x-java", "application/x-java-class"},
					{"application/x-java", "application/x-java-vm"},
					{"application/javascript", "application/x-javascript"},
					{"application/javascript", "text/javascript"},
					{"application/x-kexiproject-sqlite3", "application/x-vnd.kde.kexi"},
					{"application/x-kexiproject-sqlite3", "application/x-kexiproject-sqlite"},
					{"application/x-lha", "application/x-lzh-compressed"},
					{"text/vnd.trolltech.linguist", "application/x-linguist"},
					{"application/x-lyx", "text/x-lyx"},
					{"application/x-mozilla-bookmarks", "application/x-netscape-bookmarks"},
					{"application/annodex", "application/x-annodex"},
					{"video/annodex", "video/x-annodex"},
					{"audio/annodex", "audio/x-annodex"},
					{"application/ogg", "application/x-ogg"},
					{"audio/ogg", "audio/x-ogg"},
					{"video/ogg", "video/x-ogg"},
					{"audio/x-vorbis+ogg", "audio/vorbis"},
					{"audio/x-vorbis+ogg", "audio/x-vorbis"},
					{"audio/x-flac+ogg", "audio/x-oggflac"},
					{"video/x-theora+ogg", "video/x-theora"},
					{"video/x-ogm+ogg", "video/x-ogm"},
					{"application/vnd.palm", "application/x-palm-database"},
					{"application/pkcs12", "application/x-pkcs12"},
					{"application/x-quicktime-media-link", "application/x-quicktimeplayer"},
					{"application/x-rar", "application/x-rar-compressed"},
					{"text/x-reject", "application/x-reject"},
					{"application/x-rpm", "application/x-redhat-package-manager"},
					{"application/x-shellscript", "text/x-sh"},
					{"application/vnd.adobe.flash.movie", "application/x-shockwave-flash"},
					{"application/vnd.adobe.flash.movie", "application/futuresplash"},
					{"application/vnd.nintendo.snes.rom", "application/x-snes-rom"},
					{"application/x-stuffit", "application/stuffit"},
					{"application/x-stuffit", "application/x-sit"},
					{"application/x-subrip", "application/x-srt"},
					{"text/x-iMelody", "audio/x-iMelody"},
					{"text/x-iMelody", "audio/iMelody"},
					{"application/x-smaf", "application/vnd.smaf"},
					{"audio/x-xmf", "audio/xmf"},
					{"audio/x-xmf", "audio/mobile-xmf"},
					{"application/x-tar", "application/x-gtar"},
					{"text/troff", "application/x-troff"},
					{"text/troff", "text/x-troff"},
					{"application/zip", "application/x-zip-compressed"},
					{"application/zip", "application/x-zip"},
					{"audio/vnd.dts", "audio/x-dts"},
					{"audio/vnd.dts.hd", "audio/x-dtshd"},
					{"audio/x-aifc", "audio/x-aiffc"},
					{"audio/flac", "audio/x-flac"},
					{"audio/midi", "audio/x-midi"},
					{"audio/mp4", "audio/x-m4a"},
					{"video/mp4", "video/mp4v-es"},
					{"video/mp4", "video/x-m4v"},
					{"video/3gpp", "video/3gp"},
					{"video/3gpp", "audio/3gpp"},
					{"video/3gpp", "video/3gpp-encrypted"},
					{"video/3gpp", "audio/3gpp-encrypted"},
					{"video/3gpp", "audio/amr"},
					{"video/3gpp", "audio/amr-encrypted"},
					{"video/3gpp", "audio/amr-wb"},
					{"video/3gpp", "audio/amr-wb-encrypted"},
					{"video/3gpp", "audio/x-rn-3gpp-amr"},
					{"video/3gpp", "audio/x-rn-3gpp-amr-encrypted"},
					{"video/3gpp", "audio/x-rn-3gpp-amr-wb"},
					{"video/3gpp", "audio/x-rn-3gpp-amr-wb-encrypted"},
					{"video/3gpp2", "audio/3gpp2"},
					{"audio/mp2", "audio/x-mp2"},
					{"audio/mpeg", "audio/x-mp3"},
					{"audio/mpeg", "audio/x-mpeg"},
					{"audio/mpeg", "audio/mp3"},
					{"audio/x-mpegurl", "audio/mpegurl"},
					{"audio/x-mpegurl", "application/m3u"},
					{"audio/x-mpegurl", "audio/x-mp3-playlist"},
					{"audio/x-mpegurl", "audio/m3u"},
					{"audio/x-mpegurl", "audio/x-m3u"},
					{"audio/x-ms-asx", "video/x-ms-wvx"},
					{"audio/x-ms-asx", "video/x-ms-wax"},
					{"audio/x-ms-asx", "video/x-ms-wmx"},
					{"audio/x-ms-asx", "application/x-ms-asx"},
					{"audio/x-ms-wma", "audio/wma"},
					{"audio/vnd.rn-realaudio", "audio/x-pn-realaudio"},
					{"audio/vnd.rn-realaudio", "audio/vnd.m-realaudio"},
					{"video/vnd.rn-realvideo", "video/x-real-video"},
					{"audio/x-scpls", "application/pls"},
					{"audio/x-wav", "audio/wav"},
					{"audio/x-wav", "audio/vnd.wave"},
					{"audio/x-tta", "audio/tta"},
					{"image/bmp", "image/x-bmp"},
					{"image/bmp", "image/x-MS-bmp"},
					{"image/jpeg", "image/pjpeg"},
					{"image/jp2", "image/jpeg2000"},
					{"image/jp2", "image/jpx"},
					{"image/jp2", "image/jpeg2000-image"},
					{"image/jp2", "image/x-jpeg2000-image"},
					{"application/x-docbook+xml", "application/docbook+xml"},
					{"application/x-docbook+xml", "application/vnd.oasis.docbook+xml"},
					{"image/vnd.djvu", "image/x-djvu"},
					{"image/vnd.djvu", "image/x.djvu"},
					{"image/fits", "image/x-fits"},
					{"image/vnd.microsoft.icon", "application/ico"},
					{"image/vnd.microsoft.icon", "image/ico"},
					{"image/vnd.microsoft.icon", "image/icon"},
					{"image/vnd.microsoft.icon", "image/x-ico"},
					{"image/vnd.microsoft.icon", "image/x-icon"},
					{"image/vnd.microsoft.icon", "text/ico"},
					{"image/x-ilbm", "image/x-iff"},
					{"image/vnd.zbrush.pcx", "image/x-pcx"},
					{"image/vnd.adobe.photoshop", "image/psd"},
					{"image/vnd.adobe.photoshop", "image/x-psd"},
					{"image/vnd.adobe.photoshop", "image/photoshop"},
					{"image/vnd.adobe.photoshop", "image/x-photoshop"},
					{"image/vnd.adobe.photoshop", "application/photoshop"},
					{"image/vnd.adobe.photoshop", "application/x-photoshop"},
					{"image/x-tga", "image/x-icb"},
					{"image/x-emf", "image/emf"},
					{"image/x-emf", "application/x-emf"},
					{"image/x-emf", "application/emf"},
					{"image/x-wmf", "image/wmf"},
					{"image/x-wmf", "image/x-win-metafile"},
					{"image/x-wmf", "application/x-wmf"},
					{"image/x-wmf", "application/wmf"},
					{"image/x-wmf", "application/x-msmetafile"},
					{"image/x-xpixmap", "image/x-xpm"},
					{"inode/directory", "x-directory/normal"},
					{"text/calendar", "text/x-vcalendar"},
					{"text/calendar", "application/ics"},
					{"text/vcard", "text/directory"},
					{"text/vcard", "text/x-vcard"},
					{"application/rdf+xml", "text/rdf"},
					{"application/rss+xml", "text/rss"},
					{"text/x-opml+xml", "text/x-opml"},
					{"text/csv", "text/x-comma-separated-values"},
					{"text/csv", "text/x-csv"},
					{"text/x-csrc", "text/x-c"},
					{"application/xml-dtd", "text/x-dtd"},
					{"text/x-gettext-translation", "text/x-po"},
					{"text/x-gettext-translation", "application/x-gettext"},
					{"text/x-gettext-translation-template", "text/x-pot"},
					{"text/x-google-video-pointer", "text/google-video-pointer"},
					{"text/markdown", "text/x-markdown"},
					{"text/x-matlab", "text/x-octave"},
					{"text/x-patch", "text/x-diff"},
					{"application/sql", "text/x-sql"},
					{"text/x-tex", "application/x-tex"},
					{"text/x-uuencode", "zz-application/zz-winassoc-uu"},
					{"application/xml", "text/xml"},
					{"application/xml-external-parsed-entity", "text/xml-external-parsed-entity"},
					{"video/mpeg", "video/x-mpeg"},
					{"video/mpeg", "video/x-mpeg2"},
					{"video/vnd.mpegurl", "video/x-mpegurl"},
					{"video/vnd.vivo", "video/vivo"},
					{"video/x-flic", "video/fli"},
					{"video/x-flic", "video/x-fli"},
					{"application/x-hwp", "application/vnd.haansoft-hwp"},
					{"application/x-hwt", "application/vnd.haansoft-hwt"},
					{"application/vnd.ms-asf", "video/x-ms-wm"},
					{"application/vnd.ms-asf", "video/x-ms-asf"},
					{"video/x-msvideo", "video/x-avi"},
					{"video/x-msvideo", "video/avi"},
					{"video/x-msvideo", "video/divx"},
					{"video/x-msvideo", "video/msvideo"},
					{"video/x-msvideo", "video/vnd.divx"},
					{"application/sdp", "application/x-sdp"},
					{"application/sdp", "application/vnd.sdp"},
					{"application/winhlp", "zz-application/zz-winassoc-hlp"},
					{"application/x-iwork-keynote-sffkey", "application/vnd.apple.keynote"}
			};
}
